import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const date = new Date();
  const day = date.getDate();
  const month = date.getMonth() + 1;
  const year = date.getFullYear();
  const dateString = year + "-" + month + "-" + day;
  const [data, setData] = useState({ Clues: {}, Caption: {} });

  async function getData() {
    try {
      let url = `https://gamedata.services.amuniversal.com/c/uupuz/l/U2FsdGVkX1+b5Y+X7zaEFHSWJrCGS0ZTfgh8ArjtJXrQId7t4Y1oVKwUDKd4WyEo%0A/g/tmjmf/d/${dateString}/data.json`;
      if (date.getDay() === 0) {
        url = `https://gamedata.services.amuniversal.com/c/uupuz/l/U2FsdGVkX1+b5Y+X7zaEFHSWJrCGS0ZTfgh8ArjtJXrQId7t4Y1oVKwUDKd4WyEo%0A/g/tmjms/d/${dateString}/data.json`;
      }
      const response = await fetch(url);
      const fetchedData = await response.json();
      setData(fetchedData);
    } catch (e) {
      console.error("error", e);
    }
  }

  function makeClues() {
    const clues = Object.keys(data.Clues);
    for (const [key, value] of Object.entries(clues)) {
      for (const letter of value) {
        console.log(letter);
      }
    }
  }

  useEffect(() => {
    getData();
  }, []);

  makeClues();

  return (
    <div>
      <Head>
        <title>Word Jumble</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="flex text-2xl">Daily Word Jumble Game</h1>

        <p className="text-xl">
          {month}/{day}/{year} Puzzle
        </p>

        <div>
          <h2>{data.Clues.c1}</h2>
          <h2>{data.Clues.c2}</h2>
          <h2>{data.Clues.c3}</h2>
          <h2>{data.Clues.c4}</h2>

          <h2>{data.Caption.v1}</h2>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
